import {Cart} from '../cart/index.js';
import {defaultConfigFile} from '../config/index.js';

/**
 * The static content `picopilot init` writes into a fresh cart folder.
 *
 * The single scaffolding model (US #1): the `.p8`'s `__lua__` section is exactly
 * `#include main.lua`, and the plain-Lua `main.lua` is the file the agent edits,
 * so the agent never hand-writes the cart's binary hex sections. `main.p8` is
 * built THROUGH the cart model (not a hand-written string) so init and every
 * later cart-touching command share one serializer and the output is guaranteed
 * to round-trip.
 */

/** The PICO-8 cart format version init emits (the current stable text-format version). */
const CART_VERSION = 42;

/**
 * The one line of code in the scaffolded cart. PICO-8's `#include` pulls the
 * external Lua file in at load time; keeping it the ONLY thing in `__lua__` is
 * the `#include` discipline the whole toolchain relies on.
 */
export const LUA_INCLUDE_LINE = '#include main.lua';

/**
 * Builds the scaffolded `main.p8` via the cart model. `__lua__` holds only the
 * `#include`; the cart carries no binary sections yet (a fresh cart has no gfx /
 * map / sfx / music); those are added later by the gfx/audio commands.
 */
export function mainP8(): string {
	const cart = Cart.parse(
		`pico-8 cartridge // http://www.pico-8.com\nversion ${CART_VERSION}\n__lua__\n`,
	);
	cart.setSection('lua', `${LUA_INCLUDE_LINE}\n`);
	return cart.serialize();
}

/**
 * The starter `main.lua`: a minimal but RUNNABLE cart (the `_init/_update/_draw`
 * loop the API reference calls out as load-bearing) so a fresh folder boots
 * instead of being inert. Intentionally tiny: it is a starting point the agent
 * replaces, not a demo.
 */
export function mainLua(): string {
	return `-- main.lua, the plain-Lua source picopilot's main.p8 #includes.
-- Edit THIS file; never hand-write main.p8's binary sections.

function _init()
end

function _update()
end

function _draw()
  cls()
  print("hello picopilot", 36, 60, 7)
end
`;
}

/** The scaffolded `picopilot.json` (incur config: precedence argv > config > defaults). */
export function picopilotJson(): string {
	return defaultConfigFile();
}

/**
 * The curated PICO-8 reference written to `AGENTS.md`.
 *
 * This is CONTEXT an agent loads every turn, so it is CURATED from
 * `work/notes/findings/pico8-api-reference.md`, not a dump of the manual: the
 * hard specs, the `_init/_update/_draw` loop, the fixed palette, the memory map
 * + the gfx/map overlap WARNING, the grouped most-used API, and the token
 * discipline, the things models get wrong without a reference.
 */
export function agentsMd(): string {
	return `# PICO-8 cart context (generated by \`picopilot init\`)

You are editing a PICO-8 cart with picopilot. This file is your always-loaded
reference: the constraints, the loop, the palette, the memory map (+ the overlap
warning), the most-used API, and how to stay under the token budget. It is
curated from PICO-8's manual for the things models get wrong without a reminder.

## The \`#include\` discipline (how this cart is laid out)

- \`main.p8\` is the cart. Its \`__lua__\` section is a single line: \`#include main.lua\`.
- \`main.lua\` is the plain Lua you EDIT. Never hand-write \`main.p8\`'s binary
  sections (\`__gfx__\`, \`__map__\`, \`__sfx__\`, \`__music__\`), use picopilot's
  \`gfx\` / audio commands, which edit them safely and round-trippably.

## Hard specs (the constraints that shape everything)

- Display: **128x128**, a **fixed 16-colour palette** (indices 0..15).
- Code: **Lua**, max **8192 tokens** (the #1 thing to watch). Run \`picopilot tokens\`.
- Sprites: 256 8x8 sprites in a base bank (0..127) plus a shared bank (128..255).
- Map: 128x32 tiles + a shared half that ALIASES sprites 128..255 (see below).
- Sound: 4 channels, 64 SFX slots; music is patterns of up to 4 SFX references.
- Numbers: 16.16 fixed point, range \`-32768.0 .. 32767.99\`.

## The execution loop (every cart)

- \`_init()\`: runs once at startup.
- \`_update()\`: runs every update tick at 30fps (\`_update60()\` for 60fps).
- \`_draw()\`: runs once per visible frame.

A cart with none of these is inert. Keep them defined.

## The build loop (do this every iteration, and to finish)

One change = one pass through this loop. Do NOT skip the last step:

1. Edit \`main.lua\` (or a cart section via a picopilot command).
2. \`picopilot tokens\` to watch the 8192-token budget.
3. \`picopilot verify\` (the static gate: tokens + integrity). GREEN means
   well-formed, it does NOT mean the cart runs or plays.
4. **SEE it PLAY, not just render.** A single screenshot proves a frame draws; it
   does NOT prove the game behaves. So DRIVE it and watch it change over time:
   \`picopilot playtest run\` feeds input and captures live gameplay with no cart
   edit, or add the temporary \`run\` probe below to grab specific frames. Capture
   a sequence and compare frames so you can see MOTION and STATE CHANGE, not one
   still. Probe recipe:

   \`\`\`lua
   -- TEMPORARY: screenshot a couple of frames, then signal done so run exits.
   if t==20 then extcmd("set_filename","probe_0") extcmd("screen") end
   if t==40 then extcmd("set_filename","probe_1") extcmd("screen") end
   if t==45 then printh("__PICOPILOT_DONE__") end
   \`\`\`

**Definition of done: you have driven YOUR game's core loop and confirmed its
state actually behaves, not just that it renders.** Screenshots hide logic bugs
(state that should change on an event but does not, or does not reset when it
should). So do NOT check a fixed checklist: enumerate the state transitions YOUR
specific game defines (whatever its own actions, events, and restart do), then
drive each one and confirm the before/after state is what you intended, before
AND after a full round or restart. If reading state off the screen is hard, add
a temporary \`printh\` to dump the values and confirm them directly. A green
\`verify\`, a bare \`timeout\`, or a nice-looking title is NOT done.

## Handing the finished cart to the user

When it is verified and looks right, tell the user to play it with:

\`\`\`sh
pico8 -run /absolute/path/to/main.p8
\`\`\`

(or \`picopilot run\` for a headless screenshot pass). Do NOT reach for
\`picopilot serve\` to prove your own build: that exports + serves a browser build
for SHARING a playable cart with a human, needs a cart \`__label__\`, and puts a
human-in-the-loop where none is needed. Verify with \`run\`/\`playtest\`; serve only
if the user explicitly wants a browser build. And do NOT emit extra deliverables
(summary docs, play-guides, shell scripts, ASCII banners): the deliverable is the
verified cart itself.

## The fixed 16-colour palette (index → RGB)

In a char grid, \`.\` = transparent and \`0-F\` = these indices.

| idx | hex | name        | R   | G   | B   |
|-----|-----|-------------|-----|-----|-----|
| 0   | 0   | black       | 0   | 0   | 0   |
| 1   | 1   | dark-blue   | 29  | 43  | 83  |
| 2   | 2   | dark-purple | 126 | 37  | 83  |
| 3   | 3   | dark-green  | 0   | 135 | 81  |
| 4   | 4   | brown       | 171 | 82  | 54  |
| 5   | 5   | dark-grey   | 95  | 87  | 79  |
| 6   | 6   | light-grey  | 194 | 195 | 199 |
| 7   | 7   | white       | 255 | 241 | 232 |
| 8   | 8   | red         | 255 | 0   | 77  |
| 9   | 9   | orange      | 255 | 163 | 0   |
| 10  | a   | yellow      | 255 | 236 | 39  |
| 11  | b   | green       | 0   | 228 | 54  |
| 12  | c   | blue        | 41  | 173 | 255 |
| 13  | d   | lavender    | 131 | 118 | 156 |
| 14  | e   | pink        | 255 | 119 | 168 |
| 15  | f   | peach       | 255 | 204 | 170 |

## Memory map + the gfx/map overlap warning

\`\`\`
0x0000  gfx (spritesheet, sprites 0..127)
0x1000  shared gfx / map2   <-- sprites 128..255 ALIAS the bottom half of the map
0x2000  map
0x3000  gfx flags
0x3100  music
0x3200  sfx
0x4300  user data
0x5e00  persistent cart data (256 bytes)
0x5f00  draw state
0x5f40  hardware state
0x5f80  gpio pins
0x6000  screen (8k)
\`\`\`

**Overlap warning:** sprites 128..255 (\`0x1000\`-\`0x1fff\`) occupy the SAME memory
as \`__map__\` rows 32..63. Writing a sprite in that range clobbers the map tiles
there. \`picopilot gfx set\` smart-refuses such a write when real map tiles are at
risk and nothing authorised the loss (\`--allow-map-overlap\` or \`allowMapOverlap\`
in \`picopilot.json\`), so you never silently destroy map data you cannot see.

## Most-used API (grouped)

- **Graphics:** \`cls([col])\`, \`spr(n,x,y,[w,h],[fx],[fy])\`, \`sspr(...)\`,
  \`map(cx,cy,sx,sy,cw,ch,[layer])\`, \`pset/pget\`, \`sget/sset\`,
  \`print(str,[x,y,[col]])\`, \`rect/rectfill\`, \`circ/circfill\`, \`oval/ovalfill\`,
  \`line\`, \`pal(c0,c1,[p])\`, \`palt(col,t)\`, \`camera([x,y])\`, \`clip([x,y,w,h])\`,
  \`color(col)\`, \`fillp(mask)\`, \`tline(...)\`, \`flip()\`.
- **Map / flags:** \`mget(x,y)\`, \`mset(x,y,v)\`, \`fget(n,[f])\`, \`fset(n,[f],v)\`.
- **Input:** \`btn([i,[p]])\`, \`btnp([i,[p]])\` (buttons 0..5 = left,right,up,down,O/Z,X).
- **Audio:** \`sfx(n,[channel,[offset]])\`, \`music([n,[fade,[mask]]])\`.
- **Math:** \`abs\`, \`flr\` (\`-flr(-x)\` = ceil), \`min\`, \`max\`, \`mid\`, \`rnd(x)\`,
  \`srand(x)\`, \`sgn\`, \`sqrt\`, \`sin(x)\`/\`cos(x)\` (range 0..1, sin inverted),
  \`atan2(x,y)\`.
- **Tables:** \`add\`, \`del\`, \`deli\`, \`count\`, \`all(t)\`, \`foreach(t,f)\`, \`pairs\`, \`ipairs\`.
- **Memory:** \`peek\`, \`poke\`, \`memcpy\`, \`memset\`, \`cstore\`, \`reload\`.
- **Cart data:** \`cartdata(id)\`, \`dget(i)\`, \`dset(i,v)\`.
- **Debug:** \`printh(str)\` (to host stdout, \`picopilot run\` captures it), \`stat(n)\`.

## Gotchas that silently break carts (these differ from normal Lua/math)

These compile and run but behave WRONG. They are the traps models hit most:

- \`sin(t)\`/\`cos(t)\` take TURNS (0..1), NOT radians, and \`sin\` is INVERTED for
  screen space (+y is down). A full circle is \`t: 0->1\`. Do not multiply by
  \`2*pi\`; do not re-negate \`sin\`.
- \`/\` does NOT truncate (\`5/2\`=\`2.5\`). Integer divide is \`\\\` (\`5\\2\`=\`2\`), which
  floors toward negative infinity (\`-5\\2\`=\`-3\`).
- \`rnd(x)\` returns a FLOAT in [0,x). Use \`flr(rnd(x))\` for an integer;
  \`rnd(table)\` returns a random element.
- Tables are 1-BASED. \`del(t,val)\` removes by VALUE, \`deli(t,i)\` by INDEX.
  Deleting the current item inside \`foreach\` is safe; inside an ascending
  \`for i=1,#t\` it ERRORS once the list shrinks (iterate descending, or foreach).
- Draw state PERSISTS across frames: \`camera\`, \`pal\`, \`palt\`, \`clip\`, \`color\`,
  \`fillp\` stay set until reset (no-arg form: \`camera()\`, \`pal()\`). Reset before
  the HUD or offsets/palette swaps leak.
- Numbers are 16.16 fixed point; overflow WRAPS at ~32767. Drawing coords are
  floored to integer pixels (keep true position as a float, let draw floor it).
- Variables are GLOBAL unless \`local\`. The \`x = cond and a or b\` ternary returns
  \`b\` when \`a\` is falsy (\`false\`/\`nil\`); use an explicit \`if\` then.

(The \`picopilot-code\` skill expands these, and carries per-genre code references:
platformer / puzzle-grid / twin-stick-arcade / top-down-adventure and more.)

## Token discipline (stay under 8192)

Models blow the budget by writing verbose Lua. Prefer PICO-8 shorthands:

- \`?\` for \`print\`.
- inline if: \`if(c) x=1\`.
- compound assignment: \`+=\`, \`-=\`, \`*=\`, \`/=\`.
- \`\\\` for integer divide.
- reuse locals; avoid needless globals.

Run \`picopilot tokens\` each iteration to see the count and where it goes; when
over budget, \`picopilot minify\` (safe-only) reclaims tokens without changing
behaviour.
`;
}

/**
 * One scaffolded file: its cart-relative name and its exact bytes. `init`
 * iterates these, so adding a file is a one-line change here and the tests
 * assert against this list (the "exactly these files" contract).
 */
export interface ScaffoldFile {
	readonly name: string;
	readonly content: string;
}

/**
 * The complete set of files `picopilot init` writes into a fresh cart folder,
 * in a stable order: the cart, its editable Lua, the agent-context reference,
 * and the config. Exactly FOUR files (the acceptance contract). `AGENTS.md` is
 * the cross-agent context filename; Claude Code, Codex, and others read it, so
 * one portable file beats duplicating identical content into `CLAUDE.md`.
 */
export function scaffoldFiles(): ScaffoldFile[] {
	return [
		{name: 'main.p8', content: mainP8()},
		{name: 'main.lua', content: mainLua()},
		{name: 'AGENTS.md', content: agentsMd()},
		{name: 'picopilot.json', content: picopilotJson()},
	];
}
